name: black
on: [push]
jobs:
  linter_name:
    name: Black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rickstaa/action-black@v1
        with:
          black_args: "."
