name: Checks
on: [push]
jobs:
  black:
    name: Black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rickstaa/action-black@v1
        with:
          black_args: "."
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install requirements
        run: pip install -r requirements/dev.txt
      - name: Run mypy
        run: mypy guido/__main__.py
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: "Setup docker compose"
        run: docker compose -f ./tests/integration/docker-compose.yaml up -d --wait
      - name: Install requirements
        run: pip install -r requirements/dev.txt -r requirements/base.txt .
      - name: Run pytest
        run: pytest
      - name: Run pytest integration
        run: pytest ./tests/integration/test_integration.py
